repo: go-gitea/gitea
groups:
  -
    name: BREAKING
    labels:
      - kind/breaking
  -
    name: FEATURES
    labels:
      - kind/feature
  -
    name: SECURITY
    labels:
      - kind/security
  -
    name: BUGFIXES
    labels:
      - kind/bug
  -
    name: ENHANCEMENTS
    labels:
      - kind/enhancement
      - kind/refactor
      - kind/ui
  -
    name: TESTING
    labels:
      - kind/testing
  -
    name: TRANSLATION
    labels:
      - kind/translation
  -
    name: BUILD
    labels:
      - kind/build
      - kind/lint
  -
    name: DOCS
    labels:
      - kind/docs
  -
    name: MISC
    default: true
